name: validate-sphinx-docs

inputs:
  path:
    required: true

runs:
  using: "composite"
  steps:
  - name: Validate Sphinx documentation in ${{ inputs.path }}
    uses: cor3ntin/sphinx-action@main
    with:
      docs-folder: ${{ inputs.path }}
      build-command: "sphinx-build -b html . _build -Dsuppress_warnings=toc.not_readable,ref.doc"
